ui: tape
browsers:
  - name: chrome
    version: -2..latest
  - name: firefox
    version: -2..latest
  - name: ie
    version: 9..11
  - name: microsoftedge
    version: latest
  - name: safari
    version: -2..latest
  - name: iphone
    version: -2..latest
  - name: ipad
    version: -2..latest
  - name: android
    version: -2..latest
browserify:
  - transform: babelify
scripts:
  - "build/browser/transliteration.min.js"
